In [6]:
from itertools import permutations

In [7]:
for i,j in list(permutations(range(4), 2)):
    print(i,j)

0 1
0 2
0 3
1 0
1 2
1 3
2 0
2 1
2 3
3 0
3 1
3 2


In [1]:
import torch as th
import torch.nn as nn
from torch.nn.utils import parameters_to_vector

In [13]:
model = nn.Sequential(
        nn.Linear(2, 3),
        nn.ReLU(),
        nn.Linear(3, 1)
    )
l = list(model.parameters())
l

[Parameter containing:
 tensor([[-0.1449, -0.4023],
         [ 0.1169, -0.4974],
         [-0.4563, -0.1452]], requires_grad=True),
 Parameter containing:
 tensor([-0.5411,  0.2825,  0.2986], requires_grad=True),
 Parameter containing:
 tensor([[0.4828, 0.2428, 0.3273]], requires_grad=True),
 Parameter containing:
 tensor([-0.0014], requires_grad=True)]

In [15]:

l_flatten = [th.flatten(p) for p in l]
l_flatten = tuple(l_flatten)
l_concat = th.cat(l_flatten)
l_concat

tensor([-0.1449, -0.4023,  0.1169, -0.4974, -0.4563, -0.1452, -0.5411,  0.2825,
         0.2986,  0.4828,  0.2428,  0.3273, -0.0014], grad_fn=<CatBackward0>)

In [16]:
parameters_to_vector(model.parameters())

tensor([-0.1449, -0.4023,  0.1169, -0.4974, -0.4563, -0.1452, -0.5411,  0.2825,
         0.2986,  0.4828,  0.2428,  0.3273, -0.0014], grad_fn=<CatBackward0>)

In [7]:
params = {
    "logger": {
        "classname": "salina.logger.TFLogger",
        "log_dir": "./tmp",
        "every_n_seconds": 10000,
        "modulo": 1,
        "verbose": True
    },

    "algorithm": {
        "env_seed": 432,
        "n_envs": 8,
        "n_timesteps": 16,
        "n_particles": 2,
        "max_epochs": 100,
        "discount_factor": 0.95,
        "entropy_coef": 0.001,
        "critic_coef": 1.0,
        "policy_coef": 0.1,

        "architecture": {"hidden_size": 32},
        
        "env": {
            "classname": "svpg.agents.env.make_env",
            "env_name": "CartPole-v1",
            "max_episode_steps": 100
        },

        "optimizer": {
            "classname": "torch.optim.Adam",
            "lr": 0.01
        }
    },
}

In [3]:
%pip install git+https://github.com/Anidwyd/pandroide-svpg.git@main

  Cloning https://github.com/Anidwyd/pandroide-svpg.git (to revision main) to /tmp/pip-req-build-8jke1zwc
  Running command git clone --filter=blob:none --quiet https://github.com/Anidwyd/pandroide-svpg.git /tmp/pip-req-build-8jke1zwc
  Resolved https://github.com/Anidwyd/pandroide-svpg.git to commit 2d78850fd41c123909e95c85e35da1afe511e2d6
  Preparing metadata (setup.py) ... done
  Cloning https://github.com/facebookresearch/salina.git (to revision main) to /tmp/pip-install-gdi6m82c/salina_0c7329054fdb4ae09f599a996ddb2099
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/salina.git /tmp/pip-install-gdi6m82c/salina_0c7329054fdb4ae09f599a996ddb2099
  Resolved https://github.com/facebookresearch/salina.git to commit 481e96e8b647399175cfe29313eaa64a5cea6013
  Preparing metadata (setup.py) ... done
  Cloning https://github.com/rll/rllab.git (to revision master) to /tmp/pip-install-gdi6m82c/rllab_deac6d47cfd146149633d201ae0220c5
  Running command git

In [ ]:
import sv